### PR TITLE
Fixed bp canvas buttons, dialog box 

### LINKED ISSUE #692: [Bug]: how to use BP dark mode color inconsistency
### Is there an existing issue for this?

- [x] I have searched the existing issues and couldn't find a duplicate.

### Current Behavior

Image

### Expected Behavior

the dialog box color must change as per the mode 

Image

### Steps to Reproduce

1. Go to create binding policy 
2. you will see how to use click to add dialog box 

### Additional Context/Logs

```shell

```

### PR DESCRIPTION
**Pull request by ansh7432**
### Related Issue

Fixes #692 

### Changes Made

- [x] Updated ...
- [x] Refactored ...
- [x] Fixed ...
- [ ] Added tests for ...

### Checklist
Please ensure the following before submitting your PR:
- [x] I have reviewed the project's contribution guidelines.
- [ ] I have written unit tests for the changes (if applicable).
- [ ] I have updated the documentation (if applicable).
- [x] I have tested the changes locally and ensured they work as expected.
- [x] My code follows the project's coding standards.

### Screenshots or Logs (if applicable)

[Screencast from 11-05-25 02:11:20 AM IST.webm](https://github.com/user-attachments/assets/17fa2844-9a94-4b8e-91d8-f428e82cad4a)

### CODE REVIEW

**Comment by ansh7432** [comment]
hi @kunal-511 please look into this :)

File: src/components/BindingPolicy/PolicyCanvas.tsx [hunk 1]
```diff
@@ -1920,25 +1921,37 @@ const PolicyCanvas: React.FC<PolicyCanvasProps> = ({
...
+    minWidth: '120px',
+    borderColor: isDarkTheme ? alpha(muiTheme.palette.warning.main, 0.6) : undefined,
+    color: isDarkTheme ? 'rgba(255, 255, 255, 0.9)' : undefined,
+    transition: 'all 0.2s ease',
+    '&:hover': {
+      borderColor: isDarkTheme ? muiTheme.palette.error.main : muiTheme.palette.error.main,
+      backgroundColor: isDarkTheme ? alpha(muiTheme.palette.error.main, 0.15) : alpha(muiTheme.palette.error.main, 0.05),
+      color: isDarkTheme ? 'rgba(255, 255, 255, 0.95)' : muiTheme.palette.error.main,
+      '& .MuiSvgIcon-root': {
+        transform: 'rotate(-5deg)',
```
Comment (kunal-511) [inline src/components/BindingPolicy/PolicyCanvas.tsx:1943]: remove this transform animation i don't think needed

**Comment by kunal-511** [comment]
image
remove the white border in dark mode from the labels, import, create button

**Comment by kunal-511** [comment]
@ansh7432 rest looks good
Just update things mentioned above

**Comment by kunal-511** [comment]
one more thing @ansh7432 try to keep the commit history clean. It is showing 13 commits i don't think this a good practice.

**Comment by ansh7432** [comment]
image

removed the borders and mentioned transition 

> one more thing @ansh7432 try to keep the commit history clean. It is showing 13 commits i don't think this a good practice.

wil remeber in my next PRs

**Comment by kunal-511** [comment]
@MAVRICK-1 /lgtm

**Review by manzil-infinity180 — APPROVED** [review]
