### PR TITLE
🌱 refactor: added validation and fixed access permission reset issues

### LINKED ISSUE #2133: [Bug]: User Creation Form - Password Validation Error Message and Administrator Access Permission Reset Issues
### Is there an existing issue for this?

- [x] I have searched the existing issues and couldn't find a duplicate.

### Current Behavior

**Issue 1 - Incorrect Password Error Message:**
When creating a user with a password shorter than 6 characters, the system shows a generic "Invalid password" message instead of the specific "password must be at least 5 characters long" error message.

**Issue 2 - Administrator Access Permission Reset Bug:**
When toggling "Administrator Access" ON and then OFF, the permission radio buttons remain set to "write" instead of being reset to their previous state (both "read" and "write" should be unselected, allowing the user to choose any option).

https://github.com/user-attachments/assets/029084eb-240f-4b65-82d6-574639e0f47d

### Expected Behavior

**Issue 1:**
The system should display the specific error message "password must be at least 5 characters long" when a password shorter than 5 characters is entered.

**Issue 2:**
When "Administrator Access" is toggled OFF, all permission radio buttons should be reset to their unselected state (no option selected), allowing the user to manually choose between "read" and "write" for each component.

### Steps to Reproduce

1. Go to Admin → User Management
2. Click "Add User" button
3. Enter a valid username (e.g., "testuser")
4. Enter a password with less than 5 characters (e.g., "12345")
5. Click "Add User"
6. Observe the error message shows "Invalid password" instead of the specific length requirement
7. Toggle ON "Administrator Access" checkbox
8. Observe all permissions are automatically set to "write"
9. Toggle OFF "Administrator Access" checkbox
10. Observe that permissions remain set to "write" instead of being reset to unselected state

### Additional Context/Logs

```shell

```

### PR DESCRIPTION
**Pull request by khushiiagrawal**
### Description

Fixes two issues in the Add User form:

- The backend (`backend/utils/validation.go`) enforces `len(password) >= 5` and returns “password must be at least 5 characters long.” The frontend now surfaces that exact `details` message via the Axios interceptor and user-management flow instead of the generic “Invalid password.”

- When Administrator Access is toggled off, per the expected behavior, every component permission is cleared (set to `null`) so the user can reselect read/write; previously the radios stayed stuck on “write” after toggling back.

### Related Issue

Fixes #2133

### Changes Made

- [x] Updated Axios response interceptor to prioritize `response.data.details` over generic error messages for better error visibility
- [x] Fixed admin toggle behavior to reset all permissions to `null` when Administrator Access is disabled
- [x] Refactored permission state management to support nullable permission values (`PermissionValue = 'read' | 'write' | null`)
- [x] Fixed TypeScript null safety issue in user search filter when permissions contain null values
- [x] Optimized `handlePermissionChange` callback to check for unchanged permissions before object operations
- [x] Removed inline error display from UserFormModal (errors now shown via toast notifications only, as requested)
- [x] Added helper functions `extractApiErrorMessage` and `sanitizePermissions` for better error handling and permission management

### Screenshots or Logs (if applicable)

https://github.com/user-attachments/assets/9b5eb262-b3a3-4216-a0d9-ccda62ee60f5

### Checklist

- [x] I have reviewed the project's contribution guidelines.
- [x] I have tested the changes locally and ensured they work as expected.
- [ ] I have written unit tests for the changes (if applicable) 
- [ ] I have updated the documentation (if applicable) 
- [x] My code follows the project's coding standards.

### CODE REVIEW

**Comment by clubanderson** [comment]
instead of waiting for someone to click 'add user' - why not indicate, below the password entry, that the password is not long enough? Don't give a toast message - it's too late. Give it while the person is adding a password and needs guidance.

**Comment by khushiiagrawal** [comment]
> instead of waiting for someone to click 'add user' - why not indicate, below the password entry, that the password is not long enough? Don't give a toast message - it's too late. Give it while the person is adding a password and needs guidance.

sure. should i do the same for the "user name already taken" toast or keep it like the toast ?

**Comment by clubanderson** [comment]
yeah - no toast for either of these - dynamic response is better - less frustrating I think - what do you think?

**Comment by khushiiagrawal** [comment]
> yeah - no toast for either of these - dynamic response is better - less frustrating I think - what do you think?

agree. it will be a better way to increase the user experience.
thanks!

**Comment by khushiiagrawal** [comment]
@clubanderson  @MAVRICK-1   PTAL

https://github.com/user-attachments/assets/3c5a7dbc-f661-4d46-9366-f41a29b5771c

**Comment by MAVRICK-1** [comment]
Will check at EOD

**Comment by btwshivam** [comment]
@khushiiagrawal there is missing formError prop in UserFormModal props (runtime mismatch)
also userManagement now passes formError={formError ?? undefined} to UserFormModal, but I cannot find formError added to UserFormModalProps in UserTypes.ts??

**Comment by btwshivam** [comment]
2nd validatePassword returns null for empty password unconditionally fix it

**Comment by btwshivam** [comment]
@khushiiagrawal 3rd Username uniqueness checking is case-sensitive make it normalized soo ADMIN or admin shoud be treated same

**Comment by btwshivam** [comment]
any updates..?

**Comment by khushiiagrawal** [comment]
> any updates..?

@btwshivam  I have made all the requested changes, now the validation is as it should be. Also added trim fun so that it doesn't take spaces. Improved the UI of the "Edit user" card.
Thanks, PTAL.

**Comment by btwshivam** [comment]
@khushiiagrawal Do NOT trim password inputs while typing... Either:
remove trimming in onChange and only validate length or
ttrim on blur/submit if you intentionally want to normalize (but be explicit and document it)

**Comment by btwshivam** [comment]
why you hardcoded the validateUsername and validatePassword return messages like 'Username is already taken', 'Password must be at least 5 characters long', and the "Password length is valid" ???
uses i18n

**Comment by btwshivam** [comment]
ahh too many issuess.. dont just vibe code check also what you are doing...

**Comment by btwshivam** [comment]
UserManagement passes formError to UserFormModal: formError={formError ?? undefined}. In UserFormModal the former top-of-form motion.div that rendered formError was removed! why?? Either reintroduce formError rendering in UserFormModal or remove passing the prop.

File: frontend/src/components/admin/UserFormModal.tsx [hunk 1]
```diff
@@ -358,6 +426,26 @@ const UserFormModal: React.FC<UserFormModalProps> = ({
...
+                        {passwordError}
+                      </motion.p>
+                    )}
+                    {password && !passwordError && password.length >= 5 && (
+                      <motion.p
+                        initial={{ opacity: 0, y: -5 }}
+                        animate={{ opacity: 1, y: 0 }}
+                        className="mt-1 flex items-center gap-1 text-xs text-green-500"
+                      >
+                        <FiCheck size={12} />
```
Comment (btwshivam) [inline frontend/src/components/admin/UserFormModal.tsx:445]: from where you imported ficheck icon?? i cant see any

Comment (khushiiagrawal) [reply frontend/src/components/admin/UserFormModal.tsx:445]: it is there in line 9th 
Screenshot 2025-12-09 at 2 57 34 AM

**Comment by khushiiagrawal** [comment]
PTAL /cc @btwshivam 

https://github.com/user-attachments/assets/a0cae0e6-4ef7-40c8-9cc0-7dc09599e311

**Comment by khushiiagrawal** [comment]
> @khushiiagrawal Do NOT trim password inputs while typing... Either: remove trimming in onChange and only validate length or ttrim on blur/submit if you intentionally want to normalize (but be explicit and document it)

@btwshivam  Could you please clarify how exactly you want the password field to behave regarding spaces while typing and validation? I just want to make sure I implement it as expected.
Thanks!

**Comment by khushiiagrawal** [comment]
@btwshivam PTAL and let me know what is the requirement here so that i can proceed.
appreciate your time.

**Comment by khushiiagrawal** [comment]
@clubanderson  Updated the branch, PTAL.
Thanks!

**Review by Arpit529Srivastava — APPROVED** [review]
