### PR TITLE
fixed/drag-drop

### LINKED ISSUE #518: [Bug]: In Drag and Drop instead of dragging the labels just click the labels to go directly to the binding canvas
### Current Behavior

Currently when dragging the workloads it goes towards left side and then come back to the right side after a lag of a second.

### Expected Behavior

Add a functionality that just clicking the labels it goes to the binding canvas no drag as it is getting properly handle in every browser.

### Steps to Reproduce

1. Create biding policy via drag and drop
2. Try dropping some workloads to the canvas area.

### PR DESCRIPTION
**Pull request by ansh7432**
### Related Issue

Fixes #518 

### Changes Made

- [x] Updated ...
- [x] Refactored ...
- [x] Fixed ...
- [ ] Added tests for ...

### Checklist
Please ensure the following before submitting your PR:
- [ ] I have reviewed the project's contribution guidelines.
- [ ] I have written unit tests for the changes (if applicable).
- [ ] I have updated the documentation (if applicable).
- [x] I have tested the changes locally and ensured they work as expected.
- [x] My code follows the project's coding standards.

### Screenshots or Logs (if applicable)

[Screencast from 18-04-25 11:36:37 PM IST.webm](https://github.com/user-attachments/assets/38a4517b-12fb-4fc5-96d6-da276322d621)

### CODE REVIEW

**Comment by ansh7432** [comment]
hi @kunal-511 please see the changes :)

**Comment by MAVRICK-1** [comment]
I have to check the bp

**Comment by ansh7432** [comment]
please check if need any changes @MAVRICK-1 🙂

**Comment by ansh7432** [comment]
is it done @MAVRICK-1 ?

**Comment by kunal-511** [comment]
> is it done @MAVRICK-1 ?

Let me test it

File: src/components/BindingPolicy/ClusterPanel.tsx [hunk 1]
```diff
@@ -14,22 +14,19 @@ import {
   IconButton
 } from '@mui/material';
 import AddIcon from '@mui/icons-material/Add';
-import SearchIcon from '@mui/icons-material/Search';
```
Comment (kunal-511) [inline src/components/BindingPolicy/ClusterPanel.tsx:17]: Make search icon consistent use the mui one in both the cluster and workload

File: src/components/BindingPolicy/ClusterPanel.tsx [hunk 2]
```diff
@@ -105,137 +102,106 @@ const ClusterPanel: React.FC<ClusterPanelProps> = ({
...
+      itemId = `label-${labelGroup.key}-${labelGroup.value}`;
     } else {
-      draggableId = `label-${labelGroup.key}:${labelGroup.value}`;
+      itemId = `label-${labelGroup.key}:${labelGroup.value}`;
     }
     
-    console.log(`Creating draggable label: ${draggableId} for ${labelGroup.key}:${labelGroup.value}`);
-    
-    // Check if this label is already in the canvas
-    const isInCanvas = canvasEntities.clusters.includes(draggableId);
```
Comment (kunal-511) [inline src/components/BindingPolicy/ClusterPanel.tsx:126]: Why removing this is needed check the #582

File: src/components/BindingPolicy/ClusterPanel.tsx [hunk 3]
```diff
@@ -105,137 +102,106 @@ const ClusterPanel: React.FC<ClusterPanelProps> = ({
...
-                  color: theme.palette.info.main,
-                  position: 'absolute',
-                  top: 4,
-                  right: 4
-                }}
-              />
-            </Tooltip>
-            
-            {/* Check icon when label is in canvas */}
-            {isInCanvas && (
```
Comment (kunal-511) [inline src/components/BindingPolicy/ClusterPanel.tsx:178]: Same for this code is essential to check which label item is present in the binding canvas

File: src/components/BindingPolicy/WorkloadPanel.tsx [hunk 4]
```diff
@@ -103,163 +102,156 @@ const WorkloadPanel: React.FC<WorkloadPanelProps> = ({
...
-    // Use first workload for the draggable ID
+  // Render a label item - modified to use Box instead of Draggable
+  const renderLabelItem = (labelGroup: LabelGroup) => {
+    // Use first workload for the item ID
     const firstWorkload = labelGroup.workloads[0];
-    
-    const draggableId = `label-${labelGroup.key}-${labelGroup.value}`;
-    
-    // Check if this label is already in the canvas
-    const isInCanvas = canvasEntities.workloads.includes(draggableId);
```
Comment (kunal-511) [inline src/components/BindingPolicy/WorkloadPanel.tsx:114]: same for this also

File: src/components/BindingPolicy/WorkloadPanel.tsx [hunk 5]
```diff
@@ -103,163 +102,156 @@ const WorkloadPanel: React.FC<WorkloadPanelProps> = ({
...
-                    height: 16,
-                    '& .MuiChip-label': { px: 0.5 },
-                    bgcolor: alpha(theme.palette.info.main, 0.1),
-                    color: theme.palette.info.main
-                  }}
-                />
-              </Tooltip>
-            </Box>
-            
-            {/* Check icon when label is in canvas */}
```
Comment (kunal-511) [inline src/components/BindingPolicy/WorkloadPanel.tsx:184]: same refer to the pr #582

**Review by kunal-511 — CHANGES_REQUESTED** [review]

File: src/components/BindingPolicy/ClusterPanel.tsx (hunk 2 above)
Comment (ansh7432) [reply src/components/BindingPolicy/ClusterPanel.tsx:126]: This line was removed because we've changed the interaction model from drag-and-drop to click-to-add. and it was in ```dragdropcontainer``` wait lemme add this here and update it

Comment (kunal-511) [reply src/components/BindingPolicy/ClusterPanel.tsx:126]: Okay update it we need the functionality to check the what is added

Comment (ansh7432) [reply src/components/BindingPolicy/ClusterPanel.tsx:126]: updated @kunal-511 please check it

**Comment by kunal-511** [comment]
@ansh7432 add a check icon on the right bottom of each item of cluster labels and workload labels which is added to the binding canvas

**Comment by ansh7432** [comment]
> @ansh7432 add a check icon on the right bottom of each item of cluster labels and workload labels which is added to the binding canvas refer to the pr #582

updated :)

image

**Comment by ansh7432** [comment]
is it ready to merge now ? @kunal-511

**Comment by kunal-511** [comment]
@clubanderson  /lgtm

**Comment by ansh7432** [comment]
@MAVRICK-1 can you please remove the "don't merge" label

**Comment by MAVRICK-1** [comment]
I haven't checked it   , I will do it by today

**Comment by MAVRICK-1** [comment]
@clubanderson lgtm
