### PR TITLE
solved binding error

### LINKED ISSUE #2059: [Bug]: Error in Binding object in Object explorer
### Is there an existing issue for this?

- [x] I have searched the existing issues and couldn't find a duplicate.

### Current Behavior

it gives error when binding is selected in object explorer filter

### Expected Behavior

It should not give error

### Steps to Reproduce

1. Go to '/resources'
2. select binding in object and slect namespace

### Additional Context/Logs

```shell

```

### PR DESCRIPTION
**Pull request by alokdangre**
### Description

As we have bindingpolicy option, there is no need of binding as a option to select for kinds/object
so i have removed it

### Related Issue

Fixes #2059 

### Changes Made

- [x] Updated ...
- [ ] Refactored ...
- [x] Fixed ...
- [ ] Added tests for ...

### Checklist

Please ensure the following before submitting your PR:

- [x] I have reviewed the project's contribution guidelines.
- [ ] I have written unit tests for the changes (if applicable).
- [ ] I have updated the documentation (if applicable).
- [x] I have tested the changes locally and ensured they work as expected.
- [x] My code follows the project's coding standards.

### CODE REVIEW

File: frontend/src/pages/ObjectFilterPage.tsx [hunk 1]
```diff
@@ -727,32 +733,20 @@ const ObjectFilterPage: React.FC = () => {
...
-                    resourceKinds
-                      ? [...resourceKinds].sort((a, b) => a.kind.localeCompare(b.kind))
+                    availableResourceKinds
+                      ? [...availableResourceKinds].sort((a, b) => a.kind.localeCompare(b.kind))
                       : []
                   }
                   getOptionLabel={option => option.kind}
                   onChange={handleKindsChange}
                   isOptionEqualToValue={(option, value) => option.name === value.name}
-                  ChipProps={{
```
Comment (Arpit529Srivastava) [inline frontend/src/pages/ObjectFilterPage.tsx:743]: why you have removed this?

Comment (alokdangre) [reply frontend/src/pages/ObjectFilterPage.tsx:743]: 'ChipProps' is deprecated.ts(6385)
Autocomplete.d.ts(170, 6): The declaration was marked as deprecated here.
(property) AutocompleteProps<ResourceKind, true, false, false, "div">.ChipProps?: ChipProps<"div"> | undefined
Props applied to the [Chip](vscode-file://vscode-app/c:/Users/alokd/AppData/Local/Programs/Windsurf/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) element.,
It was deprecated that's why @Arpit529Srivastava

**Review by Arpit529Srivastava — APPROVED** [review]
