### PR TITLE
Fix: Manually Installed plugin can be uploaded to marketplace 

### LINKED ISSUE #1875: [Bug]: Couldn't upload plugin to marketplace if it has already been installed manually
### Is there an existing issue for this?

- [x] I have searched the existing issues and couldn't find a duplicate.

### Current Behavior

Couldn't upload plugin to marketplace if it has already been installed manually

### Expected Behavior

Upload plugin to marketplace should work even if it has already been installed manually

### Steps to Reproduce

1. Install plugin manually
2. upload same plugin to marketplace

### Additional Context/Logs

```shell

```

### PR DESCRIPTION
**Pull request by gaurab-khanal**
### Related Issue

Fixes #1875

### Changes Made
- Add new column **isMarketplacePlugin** to table plugin_details
- Create up and down migration file for it
- Allow plugin to be uploaded to markeplace even if it is already installed locally 

https://github.com/user-attachments/assets/886240ee-12a6-487f-a66a-27756a6d83b1

### CODE REVIEW

**Comment by ngvanthanggit** [comment]
@gaurab-khanal can you attach a screenshot or screen record?

**Comment by gaurab-khanal** [comment]
@ngvanthanggit added it

File: backend/models/plugins.go [hunk 1]
```diff
@@ -24,6 +24,7 @@ type PluginDetails struct {
 	Dependencies          DependenciesList `json:"dependencies,omitempty"`
 	PluginS3Key           string           `json:"plugin_s3_key" binding:"required"`
 	FileSize              int              `json:"file_size,omitempty"`
+	IsMarketPlacePlugin   bool             `json:"isMarketplacePlugin"`
```
Comment (ngvanthanggit) [inline backend/models/plugins.go:27]: We should follow a naming convention of JSON, at least within a struct.
Choose between `isMarketplacePlugin` and `is_marketplace_plugin`, and make all the others follow the same style if needed.
